#!/bin/bash
input="data/arma3-modlist.csv"
modlist=""
ARMA3_DIR="/mnt/data/steam/"
MODS_DIR="/mnt/data/steam/SteamApps/workshop/content/107410/"
read -p "Steam User: " STEAM_USER
read -s -p "Steam Pass: " STEAM_PASS

while IFS=',' read -r f1 f2
do
  modlist="${modlist} +workshop_download_item 107410 $f1 validate"
done < "$input"
steamcmd +login ${STEAM_USER} ${STEAM_PASS} +force_install_dir ${ARMA3_DIR}  ${modlist} +quit

# sed all to lower case now pls
echo "Changing case of all mods (this can take a while)"
find ${MODS_DIR} -depth -exec rename 's/(.*)\/([^\/]*)/$1\/\L$2/' {} \;

# Loop and make symlinks where possible
while IFS=',' read -r f1 f2
do
  echo "Making symlink between ${MODS_DIR}$f1 to ${ARMA3_DIR}arma3/@$f2"
  ln -s ${MODS_DIR}$f1 ${ARMA3_DIR}arma3/@$f2
done < "$input"
