#!/bin/bash
input="/home/steam/scripts/ezlife/data/arma3-modlist.csv"
modlist=""

read -p "Steam User: " STEAM_USER
read -s -p "Steam Pass: " STEAM_PASS

while IFS=',' read -r f1 f2
do
  modlist="${modlist} +workshop_download_item 107410 $f1 validate"
done < "$input"
steamcmd +login ${STEAM_USER} ${STEAM_PASS} +force_install_dir /mnt/data/steam/  ${modlist} +quit

# sed all to lower case now pls

# Will need another loop after this
# Loop and make symlinks where possible
